### ISSUE TITLE
TypeScript and JavaScript versions out of sync.

### ISSUE THREAD

**Issue by leocavalcante** [directus/sdk-js#69]
Just noticed that TypeScript version for `getItems` and `getItem` returns the `data` from the `RequestPromise`, but JavaScript version always returns `RequestPromise`. I get a conflict because VSCode static analysis thinks that `getItems` returns a `Promise<T[]>`, but Webpack uses the JavaScript version on the final bundle then the return is actually a `RequestPromise`.

It also conflicts with itself, because [`getPermissions` returns a `RequestPromise`](https://github.com/directus/sdk-js/blob/master/src/index.ts#L926), but its implementation is a direct return-call for `getItems` which returns `Promise<T[]>`.

@jlalvarez18 are you aware of that? I can PR a fix.

A humble suggestion, since I'm just new to Directus ecosystem: I think the project could export the JavaScript from the TypeScript or just declare typings for TypeScript users, but maintaining two sources-codes for the same thing will lead to things like that...

**Comment by rijkvanzanten** [comment]
Good suggestion. I'm currently the only maintainer of the SDK-JS and I personally don't use typescript, hence the fact that I have no clue what/how/why/when would be ideal for TypeScript users. 

I'm also of the mind set that the source code of this should be as easy to understand as possible for external devs (so it's easier to contribute fixes), and I'm not sure how the added complexity that TypeScript adds to the source code will affect that.

What would be an ideal setup for typescript in the JS SDK @leocavalcante? I'd like to keep the source in "dumb" javascript if possible, but I'm open to change if that's not a good way forwards.

**Comment by leocavalcante** [comment]
Hi @rijkvanzanten, then we can remove the TS code and just add the [type declarations](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html), what you think?
Will fit both: straightforward JS code base + type hints for TS and VSCode users.

**Comment by rijkvanzanten** [comment]
Sounds good to me 👍 Better than having two unrelated sources that get out of sync 🙂

**Comment by janbiasi** [comment]
I don't get this, why don't just have one version written in TypeScript which covers everything and add all typings needed including generics to support all dev's out there? Because at the moment the typings are solved pretty bad, there are incosistent types, weird missmatches within JSDoc and uncompleted typings ... really don't get this, just have issues with this SDK, that forked it and rewrote it in TS that I can use it in our Angular 6 and React apps with TS.

**Comment by shealavington** [comment]
Quoting Rijk: 
> I'm currently the only maintainer of the SDK-JS and I personally don't use typescript, hence the fact that I have no clue what/how/why/when would be ideal for TypeScript users.

🤷‍♂️ Not sure if you missed that @Janbiasi — Maybe you're open to helping maintain the TypeScript? 😂

**Comment by janbiasi** [comment]
@shealavington yes of course, I've just worked for the last 6h on a PR, will continue over the holiday season until monday to prepare a perfect pull request including recipes for e.g. Angular, RXJS, React etc. to help making this SDK great for all dev's :)!

cc @rijkvanzanten
